
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: 'KisanSahay',
    scan: 'Scan Plant',
    history: 'History',
    weather: 'Weather',
    more: 'More',
    upload: 'Upload Photo',
    capture: 'Take Photo',
    analyzing: 'Analyzing Leaf...',
    treatment: 'Treatment',
    organic: 'Organic',
    chemical: 'Chemical',
    prevention: 'Prevention',
    confidence: 'Confidence',
    readAloud: 'Read Result',
    noHistory: 'No scans yet.',
    weatherAlert: 'Weather Alert for Farmers',
    weatherAlertText: 'High humidity expected in next 48 hours. Risk of Fungal infections in Tomato and Potato crops increases. Consider preventive spraying.',
    shopsNearby: 'Nearby Agri Shops',
    fertRecommendations: 'Fertilizer Advice',
    chatExpert: 'Chat with Expert',
    didYouKnow: 'Did You Know?',
    didYouKnowText: 'Crop rotation with legumes like peas or beans can naturally replenish soil nitrogen without expensive chemical fertilizers.',
    severityLevel: 'Severity Level',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    humidity: 'Humidity',
    windSpeed: 'Wind Speed',
    forecast: "Today's Forecast",
    partlyCloudy: 'Partly Cloudy - Good for Harvesting',
  },
  hi: {
    title: 'किसानसहाय',
    scan: 'पौधे की जांच',
    history: 'इतिहास',
    weather: 'मौसम',
    more: 'अधिक',
    upload: 'फोटो अपलोड करें',
    capture: 'फोटो लें',
    analyzing: 'पत्ते की जांच हो रही है...',
    treatment: 'उपचार',
    organic: 'जैविक',
    chemical: 'रासायनिक',
    prevention: 'बचाव के उपाय',
    confidence: 'आत्मविश्वास',
    readAloud: 'परिणाम सुनें',
    noHistory: 'अभी तक कोई जांच नहीं।',
    weatherAlert: 'किसानों के लिए मौसम की चेतावनी',
    weatherAlertText: 'अगले 48 घंटों में उच्च आर्द्रता की उम्मीद है। टमाटर और आलू की फसलों में फंगल संक्रमण का खतरा बढ़ जाता है। निवारक छिड़काव पर विचार करें।',
    shopsNearby: 'पास की कृषि दुकानें',
    fertRecommendations: 'खाद की सलाह',
    chatExpert: 'विशेषज्ञ से चैट करें',
    didYouKnow: 'क्या आप जानते हैं?',
    didYouKnowText: 'मटर या बीन्स जैसी फलियों के साथ फसल चक्र अपनाने से महंगे रासायनिक उर्वरकों के बिना मिट्टी में नाइट्रोजन की प्राकृतिक रूप से पूर्ति हो सकती है।',
    severityLevel: 'गंभीरता का स्तर',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    humidity: 'नमी',
    windSpeed: 'हवा की गति',
    forecast: 'आज का पूर्वानुमान',
    partlyCloudy: 'आंशिक रूप से बादल - कटाई के लिए अच्छा',
  },
  mr: {
    title: 'किसानसहाय',
    scan: 'रोपाची तपासणी',
    history: 'इतिहास',
    weather: 'हवामान',
    more: 'अधिक',
    upload: 'फोटो अपलोड करा',
    capture: 'फोटो काढा',
    analyzing: 'पानाची तपासणी होत आहे...',
    treatment: 'उपचार',
    organic: 'सेंद्रिय',
    chemical: 'रासायनिक',
    prevention: 'प्रतिबंधात्मक उपाय',
    confidence: 'खात्री',
    readAloud: 'निकाल ऐका',
    noHistory: 'अजून कोणतीही तपासणी नाही.',
    weatherAlert: 'शेतकऱ्यांसाठी हवामान इशारा',
    weatherAlertText: 'पुढील 48 तासांत जास्त आर्द्रतेची अपेक्षा आहे. टोमॅटो आणि बटाट्याच्या पिकांमध्ये बुरशीजन्य संसर्गाचा धोका वाढतो. प्रतिबंधात्मक फवारणीचा विचार करा।',
    shopsNearby: 'जवळील कृषी दुकाने',
    fertRecommendations: 'खताचा सल्ला',
    chatExpert: 'तज्ञांशी चॅट करा',
    didYouKnow: 'तुम्हाला माहित आहे का?',
    didYouKnowText: 'मटार किंवा बीन्स सारख्या कडधान्यांसह पीक फेरपालट केल्याने महागड्या रासायनिक खतांशिवाय जमिनीतील नायट्रोजन नैसर्गिकरित्या पुन्हा भरून काढता येते।',
    severityLevel: 'गंभीरतेची पातळी',
    low: 'कमी',
    medium: 'मध्यम',
    high: 'जास्त',
    humidity: 'आद्रता',
    windSpeed: 'वाऱ्याचा वेग',
    forecast: 'आजचा अंदाज',
    partlyCloudy: 'अंशतः ढगाळ - कापणीसाठी चांगले',
  }
};
